In [2]:
import pandas as pd

Q1 Load the dataset into t. How many rows and how many columns does it have?

In [3]:
t=pd.read_csv("Titanic-Dataset.csv")
print("Rows:", t.shape[0])
print("Cols:", t.shape[1])

Rows: 891
Cols: 12

Q2 Print all the column names. Pick any three and write in a comment what you think each one holds.

In [4]:
columnNames=t.columns
print("Column names:", columnNames)

# Sex: dtype=str => sex of passenger
#Age: dtype=int64 => age of passengers
# Fare: dtype=float64 => ticket fare for the passenger

Column names: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

Q3 Display the first 7 rows and the last 3 rows.

In [5]:
first7Rows=t.head(7)
print("First 7 rows:",first7Rows)

last3Rows=t.tail(3)
print("Last 3 rows:",last3Rows)

First 7 rows:    PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
Last 3 rows:      PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

Q4 Run t.info(). Some columns have fewer values than the total number of rows. Write down which
columns those are, and how many values are missing from each. ★

In [6]:
t.info()

# Age => 177 missing
# Cabin => 687 missing
# Embarked=> 2 missing

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

Q5 Run t.describe(). It shows fewer columns than info() listed. Write down two columns it left out,
and explain why

In [7]:
t.describe()

# Name, Ticket because their dtype=str where describe() fails as it performs only mathematical operations

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Q6 For the class column, answer all three questions below using a different function for each:
a) how many different values are there?
b) what are they?
c) how many passengers fall into each one?

In [8]:
count=t["Pclass"].nunique()
print("Different values count:",count)

values=t["Pclass"].unique()
print("Different values:",values)

passengerUnder=t["Pclass"].value_counts()
print("No. of Passenger:\n",passengerUnder)

Different values count: 3
Different values: [3 1 2]
No. of Passenger:
 Pclass
3    491
1    216
2    184
Name: count, dtype: int64

Q7 Find how many passengers were male and how many were female.

In [9]:
passengerGender=t["Sex"].value_counts()
print("Male passengers:",passengerGender.male)
print("Female passengers:",passengerGender.female)

Male passengers: 577
Female passengers: 314

Q8 In describe(), look at the age column. Compare its mean with its 50% value. Which is larger, and
what does that suggest about the passengers' ages? ★

In [10]:
t.describe()

# mean value is larger
# median is less than mean => Half of the passengers were young of age 28

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Q9 (Challenge) The age column has missing values. Using only shape and info(), work out what
percentage of age values are missing. Write the number in a comment.

In [11]:
t.info()
print(t.shape)

# total entry => 891
# available entry => 714

# unavailable percentage= (891-714)*100/891 => 19.86%

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
(891, 12)

doubts: 
a. there is no column called class => Q6
b. what does 50% or mean>50% indicate in passengers age => Q8